# Generated by Django 5.2.5 on 2025-09-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio',
        ),
    ]
